### ISSUE TITLE
T5, BART Encoder

### ISSUE THREAD

**Issue by r1ckC139** [staoxiao/RetroMAE#12]
Have you tried using T5 encoder or BART encoder instead of BERT?

**Comment by staoxiao** [comment]
No. In the current implementation, we use the last hidden state of [CLS] token to present the sentence. If using models like T5,  you should change the codes of generating sentence embedding since there is no [CLS] token in T5.

**Comment by r1ckC139** [comment]
Hi @staoxiao,
If i want to use RetroMAE for Roberta, so all i need to do is modify all Bert* to Roberta* in pretrain/enhancedDecoder.py, pretrain/modeling.py, pretrain/run.py right? Besides that, is there anything else I should change?

**Comment by staoxiao** [comment]
Hi, you just need to replace some names in pretrain/modeling.py:
self.lm.bert -> self.lm.roberta
self.lm.cls -> self.lm.lm_head

**Comment by r1ckC139** [comment]
Thank you very much for your quick response @staoxiao
