### ISSUE TITLE
有关蒸馏实验中存在的问题

### ISSUE THREAD

**Issue by Victoriaheiheihei** [staoxiao/RetroMAE#13]
你好，在[reranker](https://github.com/staoxiao/RetroMAE/tree/master/examples/reranker)的script脚本中写的--test_query_file 和 --test_file应该设置成dev对应的文件吗？还是应该设置成train的对应文件

**Comment by Victoriaheiheihei** [comment]
还有一个问题，由于训练cross-encoder需要消耗大量的算力和时间，不知道你们可否公开你们在蒸馏中所使用到的teacher_score文件呢？

**Comment by ZhengLiu101** [comment]
Cross-encoder的训练代码会在下一期更新中集中释出（这一部分的逻辑仅仅是基于简单的对比学习，并未涉及太多trick，相信会比较容易复现）。由于所在公司数据安全方面的限制，score文件暂时无法放出。以下几个数值可供复现时参考。目前RetroMAE在仅仅使用hard negative的情况下MRR@10可以达到39.0+。基于RoBERTa/ELECTRA/DEBERTA等模型rerank之后MRR@10可进一步提升至43.0+。按默认的温度系数直接基于teacher score做蒸馏就可以达到原论文报告的数值。

**Comment by tqnwhz** [comment]
> Cross-encoder的训练代码会在下一期更新中集中释出（这一部分的逻辑仅仅是基于简单的对比学习，并未涉及太多trick，相信会比较容易复现）。由于所在公司数据安全方面的限制，score文件暂时无法放出。以下几个数值可供复现时参考。目前RetroMAE在仅仅使用hard negative的情况下MRR@10可以达到39.0+。基于RoBERTa/ELECTRA/DEBERTA等模型rerank之后MRR@10可进一步提升至43.0+。按默认的温度系数直接基于teacher score做蒸馏就可以达到原论文报告的数值。

你好，请问可以透露下一期更新是什么时候呢？以及这个issue的第一个问题，在reranker的预测脚本中，使用了dev_query，不知此处是typo还是伪标签？

**Comment by staoxiao** [comment]
你好，cross-encoder的代码之前已放出。
之前版本确实存在typo，感谢指出，已更正。用于测试reranker结果时，使用dev_query，用来生成训练集结果作为teacher score时使用train_query。

**Comment by Victoriaheiheihei** [comment]
在蒸馏的时候是使用RetroMAE_MSMARCO初始化还是使用微调后的RetroMAE_MSMARCO_finetune 进行初始化呢

**Comment by Victoriaheiheihei** [comment]
此外想问下你们有计划公开DupMAE的代码吗？

**Comment by staoxiao** [comment]
你好，使用的是RetroMAE_MSMARCO， 但继续微调RetroMAE_MSMARCO_finetune也是可以的

DupMAE在投稿中，我们计划在审稿结束后release code。

**Comment by Victoriaheiheihei** [comment]
好的，谢谢

**Comment by Victoriaheiheihei** [comment]
你好我在复现蒸馏实验中发现由于self.contrastive_loss_weight 这个参数设置为0.0，导致训练时loss很小，想问下你们当初做蒸馏实验的时候只使用到了teacher_mode与student_model之间的KL_Loss吗？

**Comment by staoxiao** [comment]
使用RetroMAE_MSMARCO_finetune时只需要KL_Loss，使用RetroMAE_MSMARCO可设置一个较小的权重(e.g., 0.01)。
另外，蒸馏需要更大的train_group_size（e.g., 65）

**Comment by tqnwhz** [comment]
> 使用RetroMAE_MSMARCO_finetune时只需要KL_Loss，使用RetroMAE_MSMARCO可设置一个较小的权重(e.g., 0.01)。 另外，蒸馏需要更大的train_group_size（e.g., 65）
你好，我还有几个问题，感谢回复：
1. 请问你们有没有做过消融实验，证明蒸馏的有效性呢。蒸馏时用了更大的train_group_size，有没有可能是更多的难负例导致的效果提升？如果做过的话，在同等公平设定下，蒸馏的提升大概有多少呢？
2. 请问对于交叉编码器，你们是如何避免过拟合导致的teacher score失真呢，是根据验证集上的loss？代码里好像没有相关逻辑。
再次感谢回复。

**Comment by staoxiao** [comment]
你好，
1. 蒸馏能够缓解false negative的影响，所以使用更多hard negative对其是有益的，但对比学习使用更大的train_group_size并不会有改进。相同的设定下，蒸馏依然会有1~2个点显著的提升。

2. 对于cross-encoder，在dev集上测试准确度，实验里MRR@10会达到0.43。
