### ISSUE TITLE
RetroMAE for Roberta Model

### ISSUE THREAD

**Issue by r1ckC139** [staoxiao/RetroMAE#14]
Hi @staoxiao,
I tried to follow the instructions in https://github.com/staoxiao/RetroMAE/issues/12#issuecomment-1452956856  to implement RetroMAE for roberta model then i got some error:
1. UserWarning: DataCollatorForWholeWordMask is only suitable for BertTokenizer-like tokenizers (according to huggingface documentation this datacollator is only suitable for BertTokenizer, is there any other suitable for RobertaTokenizer ?)
2. Error (I don't know what this error is)
![image](https://user-images.githubusercontent.com/61724310/223618656-125f073f-9b75-4027-bda0-4cb822ba0c41.png)
Hope you can give me some instructions or advice to fix the above errors, thank you very much !!!

**Comment by r1ckC139** [comment]
For 1. i guess i could implement another DataCollatorForWholeWordMask for RobertaTokenizer

**Comment by staoxiao** [comment]
Hi, 
I cannot reproduce the error 2 on my machine (transformers==4.26.1). Maybe the difference is the version of transformers. Besides, noted that the tokenizer_name in preprocess.py also should be changed to roberta.

**Comment by r1ckC139** [comment]
Hi @staoxiao
After completing the pretrain model, to get the embedding of the sentence, is it correct to use the following code:
```
from transformers import AutoTokenizer, AutoModel
import torch


# Sentences we want sentence embeddings for
sentences = ['This is an example sentence', 'Each sentence is converted']

# Load model from HuggingFace Hub
tokenizer = AutoTokenizer.from_pretrained('Roberta-RetroMAE')
model = AutoModel.from_pretrained('Roberta-RetroMAE')

# Tokenize sentences
encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input, return_dict=True)

# Get first token embedding of last layer as cls token embedding
sentence_embeddings = model_output["last_hidden_state"][:, 0]

print(f"Sentence embeddings:\n {sentence_embeddings}")
```

**Comment by staoxiao** [comment]
Yes, it's right.

**Comment by r1ckC139** [comment]
Thanks you so much staoxiao,
By the way, i create a project [X-RetroMAE](https://github.com/r1ckC139/X-RetroMAE) hope will help anyone who wants to apply RetroMAE to their own language rather than English.
