### ISSUE TITLE
No positional embedding for context?

### ISSUE THREAD

**Issue by rxqy** [staoxiao/RetroMAE#16]
Hi, from the figure 2c of the RetroMAE paper,  both the h1(query) and h2(context) get its own positional embedding.
While in the code, the h1(query) part indeed gets its positional embedding.
https://github.com/staoxiao/RetroMAE/blob/87878f09b5d33889b75f55dd7b5ff5dabe4ba919/src/pretrain/modeling.py#L45-L47

but I failed to find anything related to the "absolute" flag in the decoder. So no p.e. for the decoder part?
https://github.com/staoxiao/RetroMAE/blob/87878f09b5d33889b75f55dd7b5ff5dabe4ba919/src/pretrain/enhancedDecoder.py#L42-L44

I'm wondering if I missed anything. Many thanks in advance!

**Comment by staoxiao** [comment]
Hi, thanks for your interest in our work!

In the decoder part, we reuse the BertEmbedding layer of encoder: 
![image](https://user-images.githubusercontent.com/29973524/233366474-97556d08-fc0f-4fa7-9a61-b880864ea405.png)

When adopting the input_ids as the input, BertEmbedding class will  add the position embedding automatically.
![image](https://user-images.githubusercontent.com/29973524/233366635-26d2c3df-077c-43f3-8538-00ac4c2bd406.png)
You can see the details of BertEmbedding class in this [link].(https://github.com/huggingface/transformers/blob/04ab5605fbb4ef207b10bf2772d88c53fc242e83/src/transformers/models/bert/modeling_bert.py#L180)

**Comment by rxqy** [comment]
Hi @staoxiao. I'm a bit of confused.
https://github.com/staoxiao/RetroMAE/blob/87878f09b5d33889b75f55dd7b5ff5dabe4ba919/src/pretrain/modeling.py#L55-L59
so H1 should be the query(L55) here and H2 should be the hiddens(L56), right? And they are directly passed to the "BertLayerForDecoder"  layer.

I understand that the full bert model will have the "BertEmbedding" class and the absolute embedding for the input_ids.
But I didn't find any "BertEmbedding" class in the "BertLayerForDecoder" part.

**Comment by rxqy** [comment]
Ahh I see. I missed the [embedding class ](https://github.com/staoxiao/RetroMAE/blob/87878f09b5d33889b75f55dd7b5ff5dabe4ba919/src/pretrain/modeling.py#L42-L43) here. Many thanks!
