### ISSUE TITLE
How long is the pretraining of retromae with enhanced decoding

### ISSUE THREAD

**Issue by ma787639046** [staoxiao/RetroMAE#2]
Hi, thanks for your excellent work.

As described in the Experiment Settings Section, the pretraining of retromae with enhanced decoding was finished on 8*A100 GPUs. Could you please tell us how many hours you took to complete the pretraining？

Thanks.

**Comment by staoxiao** [comment]
Hi, it takes about 2 days on wiki and bookcorpus dataset, and no more than 1 day on msmarco dataset.

**Comment by ma787639046** [comment]
Thanks a lot!
