### ISSUE TITLE
About the evaluation after pre-training on the msmarco dataset

### ISSUE THREAD

**Issue by littlewwwhite** [staoxiao/RetroMAE#31]
I tried to train and evaluate based on this script:
[RetroMAE/examples/retriever/msmarco at master · staoxiao/RetroMAE](https://github.com/staoxiao/RetroMAE/tree/master/examples/retriever/msmarco)
There is no problem in the training process, but the output results in the evaluation part are all 0, as follows:
#####################
MRR @10: 0.0
Recall @10: 0.0
MRR @50: 0.0
Recall @50: 0.0
MRR @100: 0.0
Recall @100: 0.0
MRR @500: 0.0
Recall @500: 0.0
MRR @1000: 0.0
Recall @1000: 0.0
QueriesRanked: 6980
#####################

I don't know where I went wrong. The possible problem is that I was executing the script generated by the test data of the problem data set very quickly.
This is the part:
---
torchrun --nproc_per_node 8 \
-m bi_encoder.run \
--output_dir retromae_msmarco_passage_fintune \
--model_name_or_path Shitao/RetroMAE_MSMARCO_finetune \
--test_query_file ./data/BertTokenizer_data/dev_query \
--query_max_len 32 \
--fp16 \
--do_predict \
--prediction_save_path results/ \
--per_device_eval_batch_size 256 \
--dataloader_num_workers 6 \
--eval_accumulation_steps 100
---
There are only 14 items, the test data generation of passages-parts is normal.
I don’t know if I made a mistake with the pre-training and evaluation process of the msmarco dataset or if it’s a problem with the code part, thank you.

**Comment by staoxiao** [comment]
@littlewwwhite , after pre-training, the model cannot be used to do retrieval task directly. You need to fine-tune it following https://github.com/staoxiao/RetroMAE/tree/master/examples/retriever/msmarco#train

**Comment by littlewwwhite** [comment]
Thank you for your reply, but I did follow the method in your link: https://github.com/staoxiao/RetroMAE/tree/master/examples/retriever/msmarco#train. 

it's all right until the question-inference part:

** Generate the embeddings of passages and save to results/query_reps:**
``` 
torchrun --nproc_per_node 8 \
-m bi_encoder.run \
--output_dir retromae_msmarco_passage_fintune \
--model_name_or_path Shitao/RetroMAE_MSMARCO_finetune \
--test_query_file ./data/BertTokenizer_data/dev_query \
--query_max_len 32 \
--fp16  \
--do_predict \
--prediction_save_path results/ \
--per_device_eval_batch_size 256 \
--dataloader_num_workers 6 \
--eval_accumulation_steps 100 
``` 

when I run the passage-inference scripts, it was normal. but when executing the inference-question script, only 14 results were returned. I thought there was a problem during the download and processing of the data set, but I still had the same problem after redoing the data download and processing process. , so I am confused, I would be grateful if you could help me.
