### ISSUE TITLE
关于BEIR的Zero-shot

### ISSUE THREAD

**Issue by xiami2019** [staoxiao/RetroMAE#6]
您好，很棒的工作！
有一个关于BEIR实验的问题希望向您请教，请问从代码和论文看起来BEIR的实验是需要在MSMARCO上further train一下，请问这个是BEIR的zero-shot evaluation的常规步骤吗，因为也看到一些文章是拿预训练模型直接在BEIR上做检索，这些分数会略低一些。

**Comment by staoxiao** [comment]
谢谢！
是的，在公开的MSMARCO数据集上进行fine-tune之后再在其他数据集上进行测试，可参考[BEIR原始论文](https://arxiv.org/abs/2104.08663).

**Comment by xiami2019** [comment]
感谢回复！

**Comment by xiami2019** [comment]
您好，还想再请问一下，当fine-tune好模型之后，你们是使用的哪一个脚本对BEIR评测呢，以及一些超参数（如最大长度）等是怎么设置的呢。我通过bi_encoder里的do_predict编码了corpus，但是好像repo里没有对应的query以及指标计算的部分。

**Comment by staoxiao** [comment]
Hi~, BEIR作者提供了评测脚本，可以参考其[repo](https://github.com/beir-cellar/beir).

**Comment by staoxiao** [comment]
抱歉，刚才忘记了sentencebert里默认使用的是mean pooling，需要做一些改变。你可以参考这个[repo](https://github.com/SamuelYang1/SentMAE).

**Comment by xiami2019** [comment]
好的，感谢回复
