### ISSUE TITLE
Question about knowledge distillation

### ISSUE THREAD

**Issue by jordane95** [staoxiao/RetroMAE#9]
Hi, when I'm reading your code for bi encoder training, I find the following part quiet confusing

https://github.com/staoxiao/RetroMAE/blob/db8fbca4e7d5bc38f914c20b3053f16ed0670327/src/bi_encoder/data.py#L148-L156

It seems that if we provide teacher score for training bi encoder using knowledge distillation, the passages w.r.t a query is rearranged following the order given by scores of cross-encoder, thus the annotated positive passage in the dataset may be substituted by the most high-ranked passage returned by cross-encoder? since we regard the first passage in the list as positive by convention

Is this reasonable? Or a trick used during KD?

**Comment by staoxiao** [comment]
Sorry, this is an error I forget to delete these codes. There is no need to rearrange the passages.

**Comment by jordane95** [comment]
Thanks for your answer!
Btw, would you mind providing more details on how you trained the cross-encoder reranker (e.g., code, hyperparameters)?

**Comment by staoxiao** [comment]
Hi, I just updated the example for cross-encoder, you can find it in [examples/reranker](https://github.com/staoxiao/RetroMAE/tree/master/examples/reranker).
